/**
 * Author:    Calvin Tu
 * Date:      December 2020
 * Course:    CS 4540, University of Utah, School of Computing
 * Copyright: CS 4540 and Kevin Tran and Calvin Tu - This work may not be copied for use in Academic Coursework.
 *
 * We, Kevin Tran, Calvin Tu, and Ping Cheng Chung certify that we wrote this code from scratch and did 
 * not copy it in part or whole from another source.  Any references used 
 * in the completion of the assignment are cited in my README file and in
 * the appropriate method header.
 *
 * File Contents
 * Enum with every department abbreviation at the U of U as of Spring 2021
 * Scraped from the course listings
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace URC.Models
{
    /// <summary>
    /// Department abbreviations for every department
    /// at the U of U as of Spring 2021
    /// https://student.apps.utah.edu/uofu/stu/ClassSchedules/main/1214/index.html
    /// </summary>
    public enum Departments
    {
        NONE = 0,
        ACCTG,
        AEROS,
        ANAT,
        ANES,
        ANTH,
        ARAB,
        ARCH,
        ART,
        ARTH,
        ARTX,
        ASL,
        ASTP,
        ASTR,
        ATFA,
        ATHL,
        ATMOS,
        ATSM,
        BALLE,
        BART,
        BCOR,
        BENN,
        BIO_C,
        BIOL,
        BLCHM,
        BME,
        BMI,
        BUS,
        CAMB,
        CECRT,
        CERM,
        CH_EN,
        CHEM,
        CHIN,
        CL_CV,
        CLCS,
        CMP,
        COMM,
        COMP,
        CRIM,
        CS,
        CSD,
        CTLE,
        CVEEN,
        CVP,
        DANC,
        DENT,
        DERM,
        DES,
        DESGR,
        DISAB,
        DRAW,
        DS,
        EAE,
        EAS,
        ECE,
        ECON,
        ECS,
        ED_PS,
        EDU,
        EHUM,
        ELI,
        ELP,
        ENGIN,
        ENGL,
        ENTP,
        ENVST,
        ESSF,
        ETHNC,
        FA,
        FCS,
        FILM,
        FINAN,
        FP_MD,
        FRNCH,
        GEO,
        GEOG,
        GERM,
        GERON,
        GLOBL,
        GNDR,
        GREEK,
        H_EDU,
        H_GEN,
        HINDI,
        HIST,
        HKR,
        HNKLY,
        HONOR,
        HPSCI,
        HSP,
        HUM,
        IAGE,
        INTL,
        INTMD,
        IS,
        ITAL,
        JAPAN,
        KINES,
        KOREA,
        LAS,
        LATIN,
        LAW,
        LDRSP,
        LEAP,
        LING,
        LLART,
        LLBUS,
        LLCFT,
        LLFW,
        LLHG,
        LLHL,
        LLLAN,
        LLMT,
        LLPOT,
        LLREC,
        LLWRC,
        MATH,
        MBA,
        MBIOL,
        MD_CH,
        MD_ID,
        MD_LB,
        MDCRC,
        ME_EN,
        MET_E,
        MG_EN,
        MGT,
        MHA,
        MID_E,
        MIL_S,
        MKTG,
        MSE,
        MST,
        MUSC,
        NAHTL,
        NAVJO,
        NEURO,
        NEUSC,
        NSURG,
        NUCL,
        NUIP,
        NURS,
        NV_SC,
        OBST,
        OC_TH,
        OEHS,
        OIS,
        ONCSC,
        OPHTH,
        ORTHO,
        OSHER,
        PADMN,
        PAS,
        PATH,
        PBHLT,
        PCS,
        PCTH,
        PED,
        PEPEC,
        PERS,
        PH_MD,
        PH_TH,
        PH_TX,
        PHARM,
        PHCEU,
        PHIL,
        PHOTO,
        PHS,
        PHYS,
        PHYSL,
        POLS,
        PREP,
        PRINT,
        PRT,
        PRTL,
        PRTS,
        PRTW,
        PSY,
        PSYCT,
        PTGSE,
        PUBPL,
        QAMO,
        QUECH,
        RDLGY,
        RDONC,
        RECTH,
        REDEV,
        RELS,
        RHSCI,
        RUSS,
        SBS,
        SCI,
        SCLPT,
        SOC,
        SP_ED,
        SPAN,
        SR_EL,
        STAT,
        STRAT,
        SURG,
        SUST,
        SW,
        SWCE,
        THEA,
        UGS,
        UUHSC,
        VIET,
        WLC,
        WRTG,
        YEHS
    }
}
