//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URC.Resources.dashboard", typeof(dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string generate_report {
            get {
                return ResourceManager.GetString("generate_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking For Position.
        /// </summary>
        public static string looking_for_position {
            get {
                return ResourceManager.GetString("looking_for_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open opportunities.
        /// </summary>
        public static string open_opportunities {
            get {
                return ResourceManager.GetString("open_opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print this chart.
        /// </summary>
        public static string print_this_chart {
            get {
                return ResourceManager.GetString("print_this_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor Members.
        /// </summary>
        public static string professor_members {
            get {
                return ResourceManager.GetString("professor_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Skills Distribution.
        /// </summary>
        public static string required_skill_distribution {
            get {
                return ResourceManager.GetString("required_skill_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Supply &amp; Demand.
        /// </summary>
        public static string skill_supply_demand {
            get {
                return ResourceManager.GetString("skill_supply_demand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Interests.
        /// </summary>
        public static string student_interests {
            get {
                return ResourceManager.GetString("student_interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Skills Distribution.
        /// </summary>
        public static string student_skill_distribution {
            get {
                return ResourceManager.GetString("student_skill_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Members.
        /// </summary>
        public static string stundemt_members {
            get {
                return ResourceManager.GetString("stundemt_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Popular Opportunities.
        /// </summary>
        public static string top_5_opp {
            get {
                return ResourceManager.GetString("top_5_opp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Applications.
        /// </summary>
        public static string total_application {
            get {
                return ResourceManager.GetString("total_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Opportunities.
        /// </summary>
        public static string total_opportunities {
            get {
                return ResourceManager.GetString("total_opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        public static string visitor {
            get {
                return ResourceManager.GetString("visitor", resourceCulture);
            }
        }
    }
}
